### ISSUE TITLE
Improve and add more Documentation

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1025]
**Is your feature request related to a problem? Please describe.**
Be it new developers in the project or external partners who want to use the Clouditor via the API, the documentation is missing quiet a bit of information.

**Describe the solution you'd like**
- Improve main README (on project level)
- Add README in other important places , e.g. in the API folder
- Add a documentation folder with pages for more details; which can be referenced by the READMEs (e.g. how an auth flow work)
- Add code of conduct
- Add coding convention

```[tasklist]
### Tasks
- [ ] #581 
- [ ] https://github.com/clouditor/clouditor/issues/1028
- [ ] https://github.com/clouditor/clouditor/issues/1029
- [ ] https://github.com/clouditor/clouditor/issues/1030
- [ ] https://github.com/clouditor/clouditor/issues/1031
```
