### ISSUE TITLE
Migrate to Connect RPC

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#1337]
Migrate our internal communication from gRPC to Connect RPC. We can/should do this in several steps

```[tasklist]
### Tasks
- [ ] Switch to gRPC implementation of Connect RPC
- [ ] Replace gRPC-REST-Gateway with https://github.com/connectrpc/vanguard-go
- [ ] Remove gRPC protocol and switch to pure connect RPC protocol
- [ ] Remove gRPC dependencies
```
