### ISSUE TITLE
Support conformance check of a CSAF trusted provider

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#1414]
Because of the increasing usage of the CSAF standard, some of the bigger companies are starting to provide a CSAF trusted provider in order to disclose security advisories. This also matches to certain controls handling with vulnerability management and incident response in the usual cloud security catalogs. We should therefore support some kind of conformance checking, whether a company or a cloud service provides a correct, secure and conformant CSAF trusted provider service. We could leverage https://github.com/csaf-poc/csaf_distribution as an API (see https://github.com/csaf-poc/csaf_distribution/issues/367 for some discussions on the pro and cons of this).

The following steps would be necessary to implement this in Clouditor

```[tasklist]
### Tasks
- [ ] https://github.com/clouditor/clouditor/issues/1415
- [ ] https://github.com/clouditor/clouditor/issues/1416
- [ ] https://github.com/clouditor/clouditor/issues/1417
- [ ] https://github.com/clouditor/clouditor/issues/1418
- [ ] https://github.com/clouditor/clouditor/issues/1425
- [ ] https://github.com/clouditor/clouditor/issues/1426
- [ ] https://github.com/clouditor/clouditor/pull/1437
- [ ] https://github.com/clouditor/clouditor/issues/1441
- [ ] https://github.com/clouditor/clouditor/pull/1438
- [ ] https://github.com/clouditor/clouditor/pull/1439
```
