### ISSUE TITLE
Implement metrics for checking a CSAF publisher

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#1416]
```[tasklist]
### Tasks
- [x] Requirement 1: Valid content
- [x] Requirement 2: Valid filename
- [ ] Requirement 3: TLS
- [ ] Requirement 4: WHITE freely accesible
```
