### ISSUE TITLE
Implement metrics for checking a CSAF provider

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#1441]
```[tasklist]
### Tasks
- [ ] https://github.com/clouditor/clouditor/issues/1416
- [x] Requirements 5-7: Access restriction for red/amber, no redirect (optional) and valid provider-metadata.json
- [x] Requirements 8-10: One of them needs to be fulfilled. In our metric this is basically the case if we have a valid provider-metadata.json as we are only discovering them from these places
- [x] Requirements 11-14 (or 15-17 for ROLIE): We only have directory support for now
```
